# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ncchen99/Hugo_Blog"

[social.params]
icon = "brand-github"

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://www.facebook.com/ncchen99/"

[social.params]
icon = "brand-facebook"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/ncchen.foss"

[social.params]
icon = "brand-instagram"

